### ISSUE TITLE
error:  str type expected (type=type_error.str)

### ISSUE THREAD

**Issue by quantumalchemy** [IntelligenzaArtificiale/hugging-chat-api-LLM-custom-Wrapper#2]
Traceback (most recent call last):
  File "/app/privateGPT/HCA_test.py", line 18, in <module>
    response = llm("hello")
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 878, in __call__
    self.generate(
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 658, in generate
    output = self._generate_helper(
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 546, in _generate_helper
    raise e
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 533, in _generate_helper
    self._generate(
  File "/usr/local/lib/python3.10/site-packages/from HCA import HCA

llm = HCA(email="YOUR_EMAIL", password="YOUR_PASSWORD")
response = llm("Hello, how are you?")
print(response)", line 1057, in _generate
    generations.append([Generation(text=text)])
  File "/usr/local/lib/python3.10/site-packages/langchain/load/serializable.py", line 90, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

### reproduce:
from HCA import HCA

llm = HCA(email="YOUR_EMAIL", password="YOUR_PASSWORD")
response = llm("Hello, how are you?")
print(response)

## Thanks for doing this - much needed -

**Comment by shahzain110** [comment]
If you are facing this issue goto the file `HCA.py` and in `_call` function change the response type to `str`.

`return str(resp)`
